### ISSUE TITLE
New Issues

### ISSUE THREAD

**Issue by xrdrsp** [Dovuque/Dovuque.github.io#3]
image: <img width="661" alt="61DC7085D1DD2F330FEA48C239EF5C9F" src="https://user-images.githubusercontent.com/60511258/76185775-30233f00-620b-11ea-9dfc-f7f3f4971479.png">

> ꓒꓢꓤꓷꓤꓫ  13:36:57
https://dovuque.github.io/akp1001/
ꓒꓢꓤꓷꓤꓫ  13:37:14
标题的链接坏了

**Comment by xrdrsp** [comment]
@Dovuq 请修复。

**Comment by Dovuq** [comment]
em......

**Comment by Dovuq** [comment]
> image: 
> 
>> ꓒꓢꓤꓷꓤꓫ  13:36:57
>> https://dovuque.github.io/akp1001/
>> ꓒꓢꓤꓷꓤꓫ  13:37:14
>> 标题的链接坏了

Yes

**Comment by Dovuq** [comment]
+3 points

**Comment by xrdrsp** [comment]
@Dovuq 
Eh.

**Comment by Dovuq** [comment]
> @Dovuq
> Eh.

Now?

**Comment by Dovuq** [comment]
CIIOK.

**Comment by Dovuq** [comment]
@xrdrsp, 刷~~旧~~一下
